// V2026 Schemas
const MESSAGE_TYPES = {
  SECONDS: 'T',
  DIRECTORY: 'R',
  DIRECTORY_EXT: 'X',
  COMBINATION_LEG: 'M',
  TICK_SIZE: 'L',
  SYSTEM_EVENT: 'S',
  ORDER_BOOK_STATE: 'O',
  ADD_ORDER_ANONYMOUS: 'A',
  ADD_ORDER_ATTRIBUTED: 'F',
  ORDER_EXECUTED: 'E',
  ORDER_EXECUTED_PRICE: 'C',
  ORDER_DELETE: 'D',
  TRADE: 'P',
  EQUILIBRIUM_PRICE: 'Z',
  GLIMPSE_SNAPSHOT: 'G'
};

module.exports = {
  MESSAGE_TYPES
};
