const MESSAGE_TYPES = {
  TIME_STAMP: 'T',
  SYSTEM_EVENT: 'S',
  TRADING_SCHEDULE: 's',
  PRICE_TICK_SIZE: 'L',
  QUANTITY_TICK_SIZE: 'M',
  ORDERBOOK_DIRECTORY: 'R',
  ORDERBOOK_RESTRICTIONS: 'k',
  INDEX_MEMBER: 'Y',
  INDEX_VALUE: 'Z',
  ORDERBOOK_TRADING_ACTION: 'H',
  ADD_ORDER: 'A',
  ORDER_EXECUTED: 'E',
  ORDER_EXECUTED_BROKER: 'e',
  ORDER_EXECUTED_PRICE: 'C',
  ORDER_EXECUTED_PRICE_BROKER: 'c',
  BROKEN_TRADE: 'B',
  ORDER_DELETE: 'D',
  ORDER_REPLACE: 'U',
  INDICATIVE_PRICE_QTY: 'I',
  TRADE: 'P',
  TRADE_BROKER: 'p',
  FOREIGN_SHARES: 'f',
  BBO_QUOTATION: 'O',
  NEWS_ITEM: 'N'
};

module.exports = {
  MESSAGE_TYPES
};
